---
title: "Technologie NoSQL"
author: "Artur Koliński, Dariusz Buszman"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Przedstawienie projektu
Projekt powstał w celu zobrazowania zależności pomiędzy ilością populacji w mieście a ilością różnych środków transportu. Pod uwagę wybraliśmy kilka kluczowych miast, są to kolejno : Gdańsk, Warszawa, Szczecin, Kraków.

### Przykładowe rekordy danych (przed obróbką)
<div class = "row">
<div class = "col-md-6">

```bash
> db.stops.findOne()
{
        "_id" : ObjectId("591773abe72483b56bf4a763"),
        "id" : 179870732,
        "lon" : 20.9803952,
        "lat" : 52.2751308,
        "name" : "Marymont - Potok 03",
        "type" : "tram_stop",
        "kind" : "railway"
}
```

|    Nazwa Pola      |Opis                  | 
|--------------------|----------------------|
|lon|Długość geograficzna przystanku|
|lat|Szerokość geograficzna przystanku|
|name|Skrócona nazwa przystanku|
|type|Klucze pochodzące z OSM|
|kind|Wartości pochodzące z OSM|
|fkey|Klucz obcy z tabeli cities|
</div>
<div class = "col-md-6">

```bash
> db.cities.findOne()
{
        "_id" : ObjectId("5917739fe72483b56bf4a747"),
        "Id" : 1,
        "Miasto" : "Gdansk",
        "Lon" : 18.617162,
        "Lat" : 54.362722,
        "Populacja" : 464
}
```
|    Nazwa Pola      |         Opis         | 
|--------------------|----------------------|
|Miasto|Nazwa miasta|
|Lon|Długość geograficzna miasta|
|Lat|Szerokość geograficzna miasta|
|Populacja|Liczba ludności w całym mieście (tysiące)|
</div>
</div>
## Wstępna obróbka danych
Korzystając z programu napisanego w C# oraz dzięki wykorzystaniu specjalnych bibliotek jesteśmy w stanie bardzo szybko przerobić dużą ilość danych. Obróbka polega na podpięciu odpowiedniego Foreign Key miasta dla każdego przystanku oraz utworzeniu nowego csv powiększonego o kolumnę fkey. 
Dane po tak przeprowadzonej obróbce wyglądają następująco:
```bash
> db.stops.findOne()
{
        "_id" : ObjectId("591773abe72483b56bf4a763"),
        "id" : 179870732,
        "lon" : 20.9803952,
        "lat" : 52.2751308,
        "name" : "Marymont - Potok 03",
        "type" : "tram_stop",
        "kind" : "railway",
        "fkey" : 2
}
```

## Źródło danych
Dane z których korzystamy pochodzą z [OpenStreetMap](openstreetmap.org), ze zbioru wszystkich danych z Polski -> [Źródło](http://download.geofabrik.de/europe/poland-latest.osm.bz2).

W celu ograniczenia danych ze względu na temat projektu wykorzystaliśmy narzędzie [Osmfilter](http://wiki.openstreetmap.org/wiki/Osmfilter) udostępniane przez OpenStreetMap.

Otrzymane dane do pobrania znajdują się [->tutaj](https://1drv.ms/u/s!Ah-suCt39jqQ0s9D0aqPlX0xrQrJow)

Następnie otrzymane dane zostały rozszerzone o informację o kluczu obcym z tabeli zawierającej największe miasta w Polsce. Rozszerzenie oraz przeparsowanie danych do formaty CSV zostało wykonane przy użyciu własnego programu napisanego w jezyku C#.

## Parametry komputerów
Badań dokonaliśmy na jednym komputerze. Róznice w sprzęcie są na tyle małe, że nie ma potrzeby porównywania czasu wykonania poszczególnych zapytań na obu komputerach.

<div class = "row">
<div class = "col-md-6">

Komputer Artura

|Nazwa|Wartość|
|---|---|
|System Operacyjny|Windows 10 x64|
|Procesor|Intel Core i5-6600k|
|Ilość rdzeni|4 Cores/8 Threads|
|Pamięć|16gb ddr4|
|Dysk|256 ssd|

</div>
<div class = "col-md-6">

Komputer Darka 

|Nazwa|Wartość|
|---|---|
|System Operacyjny|Windows 10 x64|
|Procesor|Intel Core i7-3632QM|
|Ilość rdzeni|4 Cores/8 Threads|
|Pamięć|16gb ddr4|
|Dysk|256 ssd|

</div>
</div>

## Złączenie kolekcji w jedną
Aby złączyć dane z kolekcji cities i stops w jedną, wspólną kolekcję wynikową, wykonaliśmy agregację, która zapisała do kolekcji o nazwie temporary.

## Agregacja
Agregacja ta dzieli się na trzy etapy. Pierwszy etap, findData, dołącza dane z cities do kolekcji stops. W następnym etapie add2Fields użyty został addFields w celu dodania dwóch pól: miasto, populacja. Ostatni, save, zapisuje wynik poprzednich etapów do kolekcji o nazwie temporary.
```bash
findData =
{
  $lookup: {
    from: "cities",
    localField: "fkey",
    foreignField: "Id",
    as: "City"
  }
}

add2Fields =
{
  $addFields: {
    "miasto": "$City.Miasto",
    "populacja": "$City.Populacja"
  }
}

save =
{
  $out: "temporary"
}

db.stops.aggregate( [ findData, add2Fields, save ] )
```
### Wynik
Dane po tak wykonanej agregacji wyglądają następująco
```bash
> db.temporary.count()
64991
> db.temporary.findOne()
{
        "_id" : ObjectId("591773abe72483b56bf4a750"),
        "id" : 27308502,
        "lon" : 16.9168807,
        "lat" : 52.4639683,
        "name" : "Os. Sobieskiego",
        "type" : "tram_stop",
        "kind" : "railway",
        "fkey" : 9999,
        "City" : [
                {
                        "_id" : ObjectId("59178a9fe72483b56bf5a5c0"),
                        "Id" : 9999,
                        "Miasto" : "Brak",
                        "Lon" : 19.5,
                        "Lat" : 50.05,
                        "Populacja" : 1
                }
        ],
        "miasto" : [
                "Brak"
        ],
        "populacja" : [
                1
        ]
}
```
###Czas pracy
Komputer Artura: ~ 8s (małe dane)
Komputer Artura: ~ 1min 45s (duże dane)

##Kolekcje w MongoDB
Po wykonaniu powyższych czynności w naszej bazie danych znajdują się trzy kolekcje.
<div class = "row">
<div class = "col-md-6">

<b>Kolekcja cities</b> (5 rekordów)
```bash
> db.cities.findOne()
{
        "_id" : ObjectId("5917739fe72483b56bf4a747"),
        "Id" : 1,
        "Miasto" : "Gdansk",
        "Lon" : 18.617162,
        "Lat" : 54.362722,
        "Populacja" : 464
}
```
|Kolekcja|Ilość rekordów|Nazwa Pliku|
|---|---|---|
|<b>stops</b> |64 991 |stops_small|
|<b>stops</b> |2 921 931 |stops_big|
```bash
> db.stops.findOne()
{
        "_id" : ObjectId("591773abe72483b56bf4a763"),
        "id" : 179870732,
        "lon" : 20.9803952,
        "lat" : 52.2751308,
        "name" : "Marymont - Potok 03",
        "type" : "tram_stop",
        "kind" : "railway",
        "fkey" : 2
}
```

</div>
<div class = "col-md-6">
|Kolekcja|Ilość rekordów|
|---|---|
|<b>temporary</b> |64 991 |
|<b>temporary</b> |2 921 931 |
```bash
> db.temporary.findOne()
{
        "_id" : ObjectId("591773abe72483b56bf4a750"),
        "id" : 27308502,
        "lon" : 16.9168807,
        "lat" : 52.4639683,
        "name" : "Os. Sobieskiego",
        "type" : "tram_stop",
        "kind" : "railway",
        "fkey" : 9999,
        "City" : [
                {
                        "_id" : ObjectId("59178a9fe72483b56bf5a5c0"),
                        "Id" : 9999,
                        "Miasto" : "Brak",
                        "Lon" : 19.5,
                        "Lat" : 50.05,
                        "Populacja" : 1
                }
        ],
        "miasto" : [
                "Brak"
        ],
        "populacja" : [
                1
        ]
}
```

</div>
</div>

##Tworzenie próbki danych
Poniższe agregacje mają na celu utworzenie kolekcji, które przechowują po 2000 losowych przystanków.

By wyłowić 2000 przystanków z kolekcji stops, musimy wylosować 2000 rekordów z pierwszej z kolekcji stops, a następnie dla każdego z nich wydobyć i zapisać odpowiedni miasto z kolekcji cities.

Kolekcja temporary skraca ten proces, jako że wystarczy wylosować 2000 rekordów i już otrzymuje się wszystkie potrzebne dane.

<div class = "row">
<div class = "col-md-6">

```bash
mySample =
{ "$sample" : { "size" : 2000 } }
```

<b>Kolekcja temporary</b>
```bash
smallTemp =
{ "$out" : "smallTemp" }

db.temporary.aggregate( [mySample, smallTemp] )
```

<b>Wynik</b>
```bash
> db.smallTemp.count()
2000
> db.smallTemp.findOne()
{
        "_id" : ObjectId("591773abe72483b56bf5919d"),
        "id" : NumberLong("4286273872"),
        "lon" : 19.9606441,
        "lat" : 50.1310219,
        "name" : "Na Czekaj",
        "type" : "bus_stop",
        "kind" : "highway",
        "fkey" : 4,
        "City" : [
                {
                        "_id" : ObjectId("59178a9fe72483b56bf5a5bf"),
                        "Id" : 4,
                        "Miasto" : "Krakow",
                        "Lon" : 19.958868,
                        "Lat" : 50.058229,
                        "Populacja" : 765
                }
        ],
        "miasto" : [
                "Krakow"
        ],
        "populacja" : [
                765
        ]
}
```

</div>
</div>
###Czas tworzenia próbek
Komputer Artura: < 4s

##Agregacje
Szukamy trzech miast z największą liczbą przystanków, nie bierzemy pod uwagę miasta "Brak".

Wszystkie podane czasy są uśrednionym wynikiem na podstawie od trzech do pięciu prób.

```bash
matchCity =
{ "$match" : { 
    "miasto" : { "$ne" : "Brak" } 
  } 
}

group =
{
  "$group" : {
    _id : "$miasto" , count: { $sum: 1 }
  }
}

sortByStops =
{ "$sort" : { "count" : -1 } }

limitStops =
{ "$limit" : 3 }

db.smallTemp.aggregate( [ matchCity, group, sortByStops, limitStops ] )
db.temporaty.aggregate( [ matchCity, group, sortByStops, limitStops ] )
```

Czas wykonania < 10s

###Output
```bash
{ "_id" : [ "Warszawa" ], "count" : 252798 }
{ "_id" : [ "Krakow" ], "count" : 123227 }
{ "_id" : [ "Gdansk" ], "count" : 112632 }
```
//TODO interpretacja wyniku

##Agregacja
Następnie sprawdzamy ile dla każdego miasta jest punktów różnego typu i zwracamy je w liście posortowanej po ilości danego typu.

```bash
matchCity =
{ "$match" : { 
    "miasto" : { "$ne" : "Brak" } 
  } 
}

group2 =
{
  "$group" : {
    _id : {miasto: "$miasto",type: "$type"}, 
    count: { $sum: 1 }
  }
}

sortByStops =
{ "$sort" : { "count" : -1 } }

db.smallTemp.aggregate( [ matchCity, group2, sortByStops] )
db.temporary.aggregate( [ matchCity, group2, sortByStops] )
```

Czas wykonania < 10s

###Output

```bash
{ "_id" : { "miasto" : [ "Warszawa" ], "type" : "footway" }, "count" : 188368 }
{ "_id" : { "miasto" : [ "Krakow" ], "type" : "footway" }, "count" : 91722 }
{ "_id" : { "miasto" : [ "Gdansk" ], "type" : "footway" }, "count" : 85344 }
{ "_id" : { "miasto" : [ "Warszawa" ], "type" : "parking" }, "count" : 48255 }
{ "_id" : { "miasto" : [ "Szczecin" ], "type" : "footway" }, "count" : 46142 }
{ "_id" : { "miasto" : [ "Krakow" ], "type" : "parking" }, "count" : 22571 }
{ "_id" : { "miasto" : [ "Gdansk" ], "type" : "parking" }, "count" : 17974 }
{ "_id" : { "miasto" : [ "Szczecin" ], "type" : "parking" }, "count" : 13223 }
{ "_id" : { "miasto" : [ "Warszawa" ], "type" : "bus_stop" }, "count" : 6013 }
{ "_id" : { "miasto" : [ "Gdansk" ], "type" : "bus_stop" }, "count" : 4935 }
{ "_id" : { "miasto" : [ "Krakow" ], "type" : "bus_stop" }, "count" : 2506 }
{ "_id" : { "miasto" : [ "Szczecin" ], "type" : "bus_stop" }, "count" : 1447 }
```
//TODO interpretacja wyniku

##Agregacja 
//TODO opis agregacji, grupujemy parkingi, terminale, taxi i inne rzeczy 

```bash
matchCity =
{ "$match" : { 
    "miasto" : { "$ne" : "Brak" } 
  } 
}

group3 =
{
  "$group" : {
    _id : {
      miasto: "$miasto",
      type: "$type",
      fkey: "$fkey" ,
      populacja:"$populacja"
    }, 
    count: { $sum: 1 },
  }
}

project =
{
        "$project": {
            "count": 1,
            "populacja2": {
              $switch:{
               branches: [
                {case: {$eq: ["$fkey", 1]},then: 464},
                {case: {$eq: ["$fkey", 2]},then: 1754},
                {case: {$eq: ["$fkey", 3]},then: 405},
                {case: {$eq: ["$fkey", 4]},then: 765}
               ],
               default: 0
              }
            },
            "ratio": { "$divide": ["$count", "$populacja2"] },
        }
}

sortByRatio =
{ "$sort" : { "ratio" : -1 } }

db.smallTemp.aggregate( [ matchCity, group3, project, sortByRatio] )
db.temporary.aggregate( [ matchCity, group3, project, sortByRatio] )
```

Czas wykonania < 10s

###Output

```bash
{ "_id" : { "miasto" : [ "Gdansk" ], "type" : "parking", "fkey" : 1, "populacja" : [ 464 ] }, "count" : 17974, "populacja2" : 464, "ratio" : 38.73707 }
{ "_id" : { "miasto" : [ "Warszawa" ], "type" : "parking", "fkey" : 2, "populacja" : [ 1754 ] }, "count" : 48255, "populacja2" : 1754, "ratio" : 27.5114 }
{ "_id" : { "miasto" : [ "Gdansk" ], "type" : "bus_stop", "fkey" : 1, "populacja" : [ 464 ] }, "count" : 4935, "populacja2" : 464, "ratio" : 10.635775 }
{ "_id" : { "miasto" : [ "Szczecin" ], "type" : "bus_stop", "fkey" : 3, "populacja" : [ 405 ] }, "count" : 1447, "populacja2" : 405, "ratio" : 3.572839 }
{ "_id" : { "miasto" : [ "Warszawa" ], "type" : "bus_stop", "fkey" : 2, "populacja" : [ 1754 ] }, "count" : 6013, "populacja2" : 1754, "ratio" : 3.428164 }
{ "_id" : { "miasto" : [ "Krakow" ], "type" : "bus_stop", "fkey" : 4, "populacja" : [ 765 ] }, "count" : 2506, "populacja2" : 765, "ratio" : 3.275816 }
{ "_id" : { "miasto" : [ "Gdansk" ], "type" : "fuel", "fkey" : 1, "populacja" : [ 464 ] }, "count" : 750, "populacja2" : 464, "ratio" : 1.616379 }
{ "_id" : { "miasto" : [ "Krakow" ], "type" : "bicycle_parking", "fkey" : 4, "populacja" : [ 765 ] }, "count" : 1229, "populacja2" : 765, "ratio" : 1.606536 }
{ "_id" : { "miasto" : [ "Szczecin" ], "type" : "fuel", "fkey" : 3, "populacja" : [ 405 ] }, "count" : 385, "populacja2" : 405, "ratio" : 0.950617 }
{ "_id" : { "miasto" : [ "Warszawa" ], "type" : "fuel", "fkey" : 2, "populacja" : [ 1754 ] }, "count" : 1349, "populacja2" : 1754, "ratio" : 0.767959 }
{ "_id" : { "miasto" : [ "Gdansk" ], "type" : "car_wash", "fkey" : 1, "populacja" : [ 464 ] }, "count" : 332, "populacja2" : 464, "ratio" : 0.715517 }
{ "_id" : { "miasto" : [ "Gdansk" ], "type" : "bicycle_parking", "fkey" : 1, "populacja" : [ 464 ] }, "count" : 313, "populacja2" : 464, "ratio" : 0.674569 }
{ "_id" : { "miasto" : [ "Szczecin" ], "type" : "car_wash", "fkey" : 3, "populacja" : [ 405 ] }, "count" : 246, "populacja2" : 405, "ratio" : 0.607407 }
{ "_id" : { "miasto" : [ "Warszawa" ], "type" : "bicycle_parking", "fkey" : 2, "populacja" : [ 1754 ] }, "count" : 692, "populacja2" : 1754, "ratio" : 0.394527 }
{ "_id" : { "miasto" : [ "Gdansk" ], "type" : "taxi", "fkey" : 1, "populacja" : [ 464 ] }, "count" : 117, "populacja2" : 464, "ratio" : 0.252155 }
{ "_id" : { "miasto" : [ "Warszawa" ], "type" : "terminal", "fkey" : 2, "populacja" : [ 1754 ] }, "count" : 268, "populacja2" : 1754, "ratio" : 0.152794 }
{ "_id" : { "miasto" : [ "Gdansk" ], "type" : "ferry_terminal", "fkey" : 1, "populacja" : [ 464 ] }, "count" : 67, "populacja2" : 464, "ratio" : 0.1444397 }
{ "_id" : { "miasto" : [ "Szczecin" ], "type" : "terminal", "fkey" : 3, "populacja" : [ 405 ] }, "count" : 52, "populacja2" : 405, "ratio" : 0.128395 }
{ "_id" : { "miasto" : [ "Krakow" ], "type" : "taxi", "fkey" : 4, "populacja" : [ 765 ] }, "count" : 63, "populacja2" : 765, "ratio" : 0.082353 }
{ "_id" : { "miasto" : [ "Krakow" ], "type" : "terminal", "fkey" : 4, "populacja" : [ 765 ] }, "count" : 50, "populacja2" : 765, "ratio" : 0.065359 }
```
//TODO interpretacja wyniku

##Podsumowanie
//TODO ładne podsumowanie i rozeznanie w całości
